export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const GRID_CONTROLLER_BUTTON_PRESS = 'GRID_CONTROLLER_BUTTON_PRESS';
export const GRID_CONTROLLER_BUTTON_RELEASE = 'GRID_CONTROLLER_BUTTON_RELEASE';
